export const SET_USER = 'SET_USER';
export const REMOVE_USER = 'REMOVE_USER';

export const SET_CONTACTS = 'SET_CONTACTS';
export const SET_SELECTED_CONTACT = 'SET_SELECTED_CONTACT';
export const SET_CONTACTS_LOADING = 'SET_CONTACTS_LOADING';
export const SET_CONTACT_SEARCH = 'SET_CONTACTS_SEARCH';

export const SET_CHATS = 'SET_CHATS';
export const FETCHING_CHAT = 'FETCHING_CHAT';

export const VIEW_CONTACT_DETAILS = 'VIEW_CONTACT_DETAILS';
export const SET_SIDEBAR_VISIBLE = 'SET_SIDEBAR_VISIBLE';
